apiVersion: v1
kind: ServiceAccount
metadata:
  name: navigation-service
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: navigation-service@starfleet-gke-platform-lab.iam.gserviceaccount.com
